### ISSUE TITLE
Upgrade custom plugins to support 1.19.2

### ISSUE THREAD

**Issue by MOBAdmin** [DmitryRendov/mob-issues#16]
- [x] AWD
- [x] AntiXRay && XRayAnalyzer
- [x] AntiAFKPlus
- [x] BlockPluginList
- [x] HouseKeeping
- [x] GraviTree
- [x] ChunkSpawnerLimiter
- [x] PhantomAdmin

**Comment by DmitryRendov** [comment]
BlockPluginList and ChunkSpawnerLimiter are already upgraded. AntiAFKPlus had been disabled and deprecated since 1.17

**Comment by MOBAdmin** [comment]
PhantomAdmin, resolved via https://github.com/DmitryRendov/PhantomAdmin/pull/11

**Comment by MOBAdmin** [comment]
XRayMonitor, resolved via https://github.com/DmitryRendov/XRayMonitor/pull/2

**Comment by MOBAdmin** [comment]
AntiAFKPlus, resolved via https://github.com/DmitryRendov/AntiAFKPlus/pull/1

**Comment by MOBAdmin** [comment]
GraviTree, resolved via https://github.com/DmitryRendov/GraviTree/pull/14

**Comment by DmitryRendov** [comment]
HouseKeeping is done, https://github.com/DmitryRendov/HouseKeeping/pull/22
